@echo off
rem ============================================================
rem  2-create-keystore.bat — Create a PKCS12 signing keystore
rem ============================================================
rem
rem  USAGE: Run once before signing for the first time.
rem         Keep morphe.p12 safe — lose it and you can't push
rem         updates to devices that have the signed APK installed.
rem
rem  OUTPUT: morphe.p12 in this scripts\ directory
rem
rem  WHY PKCS12: morphe-cli uses BouncyCastle for signing, which is
rem  incompatible with keystores generated by JDK 9+. We skip
rem  morphe-cli signing entirely (--unsigned) and use apksigner
rem  from Android SDK instead. apksigner supports PKCS12 natively.
rem
rem  PRIVACY: The certificate contains only "CN=Morphe, O=Morphe, C=US"
rem  and a creation timestamp. No PII, no machine info, no usernames.
rem ============================================================

call "%~dp0CONFIG.bat"

if exist "%KEYSTORE%" (
    echo Keystore already exists: %KEYSTORE%
    echo Delete it first if you want to regenerate.
    exit /b 0
)

keytool -genkeypair ^
  -keystore "%KEYSTORE%" ^
  -storetype PKCS12 ^
  -alias %KS_ALIAS% ^
  -keyalg RSA -keysize 2048 -validity 10000 ^
  -storepass %KS_PASS% -keypass %KS_PASS% ^
  -dname "CN=Morphe, O=Morphe, C=US"

if errorlevel 1 (
    echo ERROR: keytool failed. Is Java installed and on PATH?
    exit /b 1
)

echo.
echo Keystore created: %KEYSTORE%
echo Store password:   %KS_PASS%
echo Key alias:        %KS_ALIAS%
echo.
echo Back this file up somewhere safe.
echo Proceed to 3-patch.bat.
